package com.testviewsoft.modelo;
// Generated 21-oct-2012 20:00:25 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentosIdentidad generated by hbm2java
 */
public class DocumentosIdentidad  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Boolean estado;
     private Date tiempoEstado;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public DocumentosIdentidad() {
    }

    public DocumentosIdentidad(String nombre, Boolean estado, Date tiempoEstado, Set<Usuarios> usuarioses) {
       this.nombre = nombre;
       this.estado = estado;
       this.tiempoEstado = tiempoEstado;
       this.usuarioses = usuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getTiempoEstado() {
        return this.tiempoEstado;
    }
    
    public void setTiempoEstado(Date tiempoEstado) {
        this.tiempoEstado = tiempoEstado;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


