package com.testviewsoft.modelo;
// Generated 27-oct-2012 18:57:02 by Hibernate Tools 3.2.1.GA



/**
 * UsuariosPaisesId generated by hbm2java
 */
public class UsuariosPaisesId  implements java.io.Serializable {


     private int usuariosId;
     private int paisesId;

    public UsuariosPaisesId() {
    }

    public UsuariosPaisesId(int usuariosId, int paisesId) {
       this.usuariosId = usuariosId;
       this.paisesId = paisesId;
    }
   
    public int getUsuariosId() {
        return this.usuariosId;
    }
    
    public void setUsuariosId(int usuariosId) {
        this.usuariosId = usuariosId;
    }
    public int getPaisesId() {
        return this.paisesId;
    }
    
    public void setPaisesId(int paisesId) {
        this.paisesId = paisesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariosPaisesId) ) return false;
		 UsuariosPaisesId castOther = ( UsuariosPaisesId ) other; 
         
		 return (this.getUsuariosId()==castOther.getUsuariosId())
 && (this.getPaisesId()==castOther.getPaisesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuariosId();
         result = 37 * result + this.getPaisesId();
         return result;
   }   


}


