package com.testviewsoft.modelo;
// Generated 27-oct-2012 18:57:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UsuariosPaises generated by hbm2java
 */
public class UsuariosPaises  implements java.io.Serializable {


     private UsuariosPaisesId id;
     private Usuarios usuarios;
     private Paises paises;
     private String gentilicio;
     private Boolean estado;
     private Date tiempoEstado;

    public UsuariosPaises() {
    }

	
    public UsuariosPaises(UsuariosPaisesId id, Usuarios usuarios, Paises paises) {
        this.id = id;
        this.usuarios = usuarios;
        this.paises = paises;
    }
    public UsuariosPaises(UsuariosPaisesId id, Usuarios usuarios, Paises paises, String gentilicio, Boolean estado, Date tiempoEstado) {
       this.id = id;
       this.usuarios = usuarios;
       this.paises = paises;
       this.gentilicio = gentilicio;
       this.estado = estado;
       this.tiempoEstado = tiempoEstado;
    }
   
    public UsuariosPaisesId getId() {
        return this.id;
    }
    
    public void setId(UsuariosPaisesId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Paises getPaises() {
        return this.paises;
    }
    
    public void setPaises(Paises paises) {
        this.paises = paises;
    }
    public String getGentilicio() {
        return this.gentilicio;
    }
    
    public void setGentilicio(String gentilicio) {
        this.gentilicio = gentilicio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getTiempoEstado() {
        return this.tiempoEstado;
    }
    
    public void setTiempoEstado(Date tiempoEstado) {
        this.tiempoEstado = tiempoEstado;
    }

    @Override
    public String toString() {
        return "UsuariosPaises{" + "id=" + id + ", usuarios=" + usuarios.toString() + ", paises=" + paises.toString() + ", gentilicio=" + gentilicio + ", estado=" + estado + ", tiempoEstado=" + tiempoEstado + '}';
    }




}


